### ISSUE TITLE
Scitech-text showing HTML code instead of processing it on eventpage

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-eventadmin#45]
I entered text with HTML for a scitech-text product, and the Admin preview renders the HTML correctly, but the eventpage is displaying all the HTML instead of processing it.

For an example, see http://earthquake.usgs.gov/earthquakes/eventpage/usp000hhuc#scientific_summary

**Comment by ehunter-usgs** [comment]
It looks like this is an issue with earthquake-eventpages and not the earthquake-eventadmin, so I am creating a new issue and closing this one.

https://github.com/usgs/earthquake-eventpages/issues/284
