### ISSUE TITLE
Add a General Header

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventadmin#59]
Add the "Add General Header" button from the "General - Summary" page to the top of the "Admin - Summary" page. 

Use the custom modal dialog that already exists for text products. This modal will be enhanced to include a radio list of available alert styles (see image). 

If you can think of how to better embed image tags or html link tags feel free.

**Comment by llastowka-usgs** [comment]
Add this to the "Add/Edit Content" page

**Comment by emartinez-usgs** [comment]
- Need to unbind event listener for addHeaderButton during destroy method.
