### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventadmin#63]
Make sure that the project builds with all the current dependencies, and lock-in specific versions. 

Move earthquake-eventpage dependency into the usgs fork, from jmfee-usgs's fork,
https://github.com/jmfee-usgs/earthquake-eventpages#eventadmin-base

Update to use:
 - browserify (instead of requirejs)
 - postcss (instead of compass)
 - eslint (instead of jshint)

**Comment by emartinez-usgs** [comment]
Still depends on: https://github.com/usgs/hazdev-cache-invalidator/pull/4

Once that is merged/released, update this project to use proper cache invalidator dependency from npm (instead of GitHub). This is necessary to get grunt running on this project.
