### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventadmin#65]
Have inputs for username/password and a button to submit. 

The login page should submit to the search page.

**Comment by emartinez-usgs** [comment]
Since login.php is a separate page from the search (index.php) or event (event.php) pages, it should get it's own "'login.scss" file rather than a partial in "index.scss".

**Comment by emartinez-usgs** [comment]
My previous comment is fixed in #79 so this can be closed if that gets merged.
