### ISSUE TITLE
Update Left Navigation

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventadmin#68]
- Add a link to return to the search page.
- Add divider after the "Admin" section, before "General", that says:
  - Legacy Functionality (bold red text)
  - Use at your own risk (small gray text)
- Move "Latest Earthquakes" link above the divider
- Add "Log out" link 

Suppress all navigation if the user is not logged in.

**Comment by ehunter-usgs** [comment]
I believe we are removing the earthquake-eventpage functionality, so we would only need:
 - Add a link to return to the search page.
 - Add "Log out" link
 - Suppress all navigation if the user is not logged in.

**Comment by llastowka-usgs** [comment]
Add section for Update/Edit Content

**Comment by emartinez-usgs** [comment]
Only thing remaining is to add a link to "Latest Earthquakes" (map/list).
