### ISSUE TITLE
Add Splash Page with Warning to Delete Pop-up

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventadmin#93]
Add a splash page that warns the user that they are about to delete an event.

"If this event is real, associate this event, do not delete."

**Comment by emartinez-usgs** [comment]
- `onContinueClick` does not need to accept products, the parameter is ignored anyway.
- When calling `onContinueClick` there is no need to provide an undefined `products` argument.
- Do not declare `products` in `onDeleteEventClick`
